In [11]:
import numpy as np

x = np.array([1,2,3,4,1000])
print(x)
print(x.shape)
print(type(x))
print(x.dtype)

x = x.astype(np.float64)
print(x)
print(x.dtype)

# weil 1000 nicht in int8 passt gibts einen overflow
x = x.astype(np.int8)
print(x)
print(x.dtype)

[   1    2    3    4 1000]
(5,)
<class 'numpy.ndarray'>
int32
[   1.    2.    3.    4. 1000.]
float64
[  1   2   3   4 -24]
int8


In [16]:
myArray = np.arange(10)
print(myArray)

myArray2 = np.linspace(start=0.0, stop=10.0, num=125)
print(myArray2)

myArray3 = np.linspace(start=0.0, stop=10.0, num=125, dtype=np.int32)
print(myArray3)

[0 1 2 3 4 5 6 7 8 9]
[ 0.          0.08064516  0.16129032  0.24193548  0.32258065  0.40322581
  0.48387097  0.56451613  0.64516129  0.72580645  0.80645161  0.88709677
  0.96774194  1.0483871   1.12903226  1.20967742  1.29032258  1.37096774
  1.4516129   1.53225806  1.61290323  1.69354839  1.77419355  1.85483871
  1.93548387  2.01612903  2.09677419  2.17741935  2.25806452  2.33870968
  2.41935484  2.5         2.58064516  2.66129032  2.74193548  2.82258065
  2.90322581  2.98387097  3.06451613  3.14516129  3.22580645  3.30645161
  3.38709677  3.46774194  3.5483871   3.62903226  3.70967742  3.79032258
  3.87096774  3.9516129   4.03225806  4.11290323  4.19354839  4.27419355
  4.35483871  4.43548387  4.51612903  4.59677419  4.67741935  4.75806452
  4.83870968  4.91935484  5.          5.08064516  5.16129032  5.24193548
  5.32258065  5.40322581  5.48387097  5.56451613  5.64516129  5.72580645
  5.80645161  5.88709677  5.96774194  6.0483871   6.12903226  6.20967742
  6.29032258  6.37096774  6.4