In [3]:
import numpy as np

myArray = np.array([1.0, 2.0, 3.0])
print(myArray)
print(len(myArray))
print(myArray.shape)


[1. 2. 3.]
3
(3,)


In [6]:
myArray = np.array([1,2,3,4])
print(myArray.shape)

myArray = np.reshape(myArray, (1,4))
print(myArray.shape)
print(myArray)

myArray = np.reshape(myArray, (4,1))
print(myArray.shape)
print(myArray)

myArray = np.reshape(myArray, (2,2))
print(myArray.shape)
print(myArray)

(4,)
(1, 4)
[[1 2 3 4]]
(4, 1)
[[1]
 [2]
 [3]
 [4]]
(2, 2)
[[1 2]
 [3 4]]


In [14]:
myZero = np.zeros(shape=(3,3))
print(myZero)

myOne = np.ones(shape=(3,3))
print(myOne)

myArray = np.full(shape=(5,5), fill_value=0.125)
print(myArray)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0.125 0.125 0.125 0.125 0.125]
 [0.125 0.125 0.125 0.125 0.125]
 [0.125 0.125 0.125 0.125 0.125]
 [0.125 0.125 0.125 0.125 0.125]
 [0.125 0.125 0.125 0.125 0.125]]


In [17]:
myArray = np.array([-1, 0, 1])

print(np.max(myArray))
print(np.min(myArray))
print(np.argmax(myArray))
print(np.argmin(myArray))

print(myZero * myOne)

myArray = np.full(shape=(3,3), fill_value=0.125)
print(np.dot(myOne, myArray))

1
-1
2
0
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0.375 0.375 0.375]
 [0.375 0.375 0.375]
 [0.375 0.375 0.375]]
